#!/bin/sh /etc/rc.common
START=99

APP=cgminer
PID_FILE=/var/run/$APP.pid


start() {
	local _pool1url
	local _pool1user
	local _pool1pw

	local _pool2url
	local _pool2user
	local _pool2pw

	local _pool3url
	local _pool3user
	local _pool3pw

	local _api_listen
	local _api_network
	local _api_allow
	local _mo

	local _ntp_enable
	local _ntp_pools

	config_load pools

	config_get _pool1url default pool1url
	config_get _pool1user default pool1user
	config_get _pool1pw default pool1pw
	config_get _pool2url default pool2url
	config_get _pool2user default pool2user
	config_get _pool2pw default pool2pw
	config_get _pool3url default pool3url
	config_get _pool3user default pool3user
	config_get _pool3pw default pool3pw

	config_get _ntp_enable default ntp_enable
	config_get _ntp_pools default ntp_pools


	config_load cgminer
	config_get _temperature_limit default temperature_limit
	config_get _fan_speed_limit default fan_speed_limit
	config_get _voltage_limit default voltage_limit
	config_get _rated_power_limit default rated_power_limit
	config_get _chip_freq_init default chip_freq_init
	config_get _work_interval default work_interval
	config_get _temp_chips default temp_chips
	config_get _temp_sensors_per_chip default temp_sensors_per_chip
	config_get _upfreq_pass_cores_percent default upfreq_pass_cores_percent
	config_get _upfreq_pass_chips_percent default upfreq_pass_chips_percent
	config_get _pre_heat_temp default pre_heat_temp
	config_get _pre_heat_end_freq default pre_heat_end_freq
	config_get _pre_heat_timeout default pre_heat_timeout

	config_get _bitmicro_options default bitmicro_options
	config_get _bitmicro_devs default bitmicro_devs

	config_get _api_listen default api_listen
	config_get _api_network default api_network
	config_get _api_allow default api_allow
	config_get _mo default more_options

	if [ "$_pool1url" != "" -a "$_pool1user" != "" -a "$_pool1pw" != "" ]; then
	    POOL1="-o $_pool1url -O $_pool1user:$_pool1pw"
	fi
	if [ "$_pool2url" != "" -a "$_pool2user" != "" -a "$_pool2pw" != "" ]; then
	    POOL2="-o $_pool2url -O $_pool2user:$_pool2pw"
	fi
	if [ "$_pool3url" != "" -a "$_pool3user" != "" -a "$_pool3pw" != "" ]; then
	    POOL3="-o $_pool3url -O $_pool3user:$_pool3pw"
	fi

	if [ "$_mo" != "" ]; then
	    VOLT_OFFSET="--bitmicro-more $_mo"
	fi

	if [ "$_api_listen" == "true" ]; then
	    API_LISTEN="--api-listen"
	else
            API_LISTEN=""
	fi 

	if [ "$_api_network" == "true" ]; then
	    API_NETWORK="--api-network"
	else
            API_NETWORK=""
	fi 

	CHIP_OPTIONS="$_bitmicro_options:$_chip_freq_init:$_work_interval"
	LIMIT_OPTIONS="$_temperature_limit:$_fan_speed_limit:$_voltage_limit:$_rated_power_limit"
	TEMP_SENSOR_OPTIONS="$_temp_chips:$_temp_sensors_per_chip"
	UPFREQ_OPTIONS="$_upfreq_pass_cores_percent:$_upfreq_pass_chips_percent"
	PRE_HEAT_OPTIONS="$_pre_heat_temp:$_pre_heat_end_freq:$_pre_heat_timeout"
	BITMICRO_OPTIONS=" --bitmicro-options $CHIP_OPTIONS:$LIMIT_OPTIONS:$TEMP_SENSOR_OPTIONS:$UPFREQ_OPTIONS:$PRE_HEAT_OPTIONS --bitmicro-devs $_bitmicro_devs"
	PARAMS="$BITMICRO_OPTIONS $POOL1 $POOL2 $POOL3 $API_LISTEN $API_NETWORK --api-allow $_api_allow --syslog"
	echo $PARAMS

	NTP_POOL="-p 3.cn.pool.ntp.org -p 2.cn.pool.ntp.org  -p 1.cn.pool.ntp.org -p 0.cn.pool.ntp.org"
	ASIA=$_ntp_pools

	# _ntp_enable: openwrt, asia, globle
	if [ "$_ntp_enable" == "asia" ]; then
	    NTP_POOL="${ASIA}"
	fi

	if [ ! -f /tmp/cgminer-ntpd-done -a "$_ntp_enable" != "disable" ]; then
	    while [ "$NTPD_RET" != "0" ]; do
		ntpd -d -n -q -N ${NTP_POOL}
		NTPD_RET=$?
	    done

	    touch /tmp/cgminer-ntpd-done
	fi

        # Make sure udevd run before cgminer start
        UDEVDCNT=`pidof udevd | wc -w`
        if [ "$UDEVDCNT" == "0" ]; then
                mkdir -p /run
                udevd --daemon
        fi

	sleep 2
	start-stop-daemon -S -x $APP -p $PID_FILE -m -b -- $PARAMS
}

stop() {
	start-stop-daemon -K -n $APP -p $PID_FILE -s TERM
	sleep 2
}
