#!/bin/sh /etc/rc.common

START=80
STOP=20

isH3Platform=false

hwmon0_path="/sys/class/hwmon/hwmon0/"
hwmon1_path="/sys/class/hwmon/hwmon1/"
hwmon2_path="/sys/class/hwmon/hwmon2/"
hwmon4_path="/sys/class/hwmon/hwmon4/"

start() {
    cpuinfo=`cat /proc/cpuinfo | grep sun8i`
    if [ "$cpuinfo" != "" ]; then
        isH3Platform=true
        echo "It's H3 platform."
    fi

    if [ isH3Platform ]; then
        hwmon0_path="/sys/class/hwmon/hwmon0/device/"
        hwmon1_path="/sys/class/hwmon/hwmon1/device/"
        hwmon2_path="/sys/class/hwmon/hwmon2/device/"
        hwmon4_path="/sys/class/hwmon/hwmon4/device/"
    fi

    # Detect hash board type
    if [ -f $hwmon0_path/name ]; then
        name0=`cat $hwmon0_path/name`
    fi
    if [ -f $hwmon1_path/name ]; then
        name1=`cat $hwmon1_path/name`
    fi
    if [ -f $hwmon2_path/name ]; then
        name2=`cat $hwmon2_path/name`
    fi

    if [ "$name0" = "tmp421" -o "$name1" = "tmp421" -o "$name2" = "tmp421" ]; then
        hash_board="HB12"
    else
        if [ -f $hwmon0_path/name ]; then
            name0=`cat $hwmon0_path/name`
        fi
        if [ -f $hwmon2_path/name ]; then
            name1=`cat $hwmon2_path/name`
        fi
        if [ -f $hwmon4_path/name ]; then
            name2=`cat $hwmon4_path/name`
        fi

        if [ "$name0" = "tmp423" -o "$name1" = "tmp423" -o "$name2" = "tmp423" ]; then
            hash_board="HB10"
        elif [ "$name0" = "lm75" -o "$name1" = "lm75" -o "$name2" = "lm75" ]; then
            hash_board="ALB10"
        else
            hash_board="unknown"
        fi
    fi

    logger "detect-cgminer-config: hash_board=$hash_board"

    if [ "$hash_board" = "unknown" ]; then
        exit 1;
    fi

    # Start linking files ...
    if [ "$hash_board" = "ALB10" ]; then
        if [ isH3Platform ]; then
            CGMINERFILE="cgminer.alb10.h3"
            CGMINERDEFAULTFILE="cgminer.default.alb10.h3"
        else
            CGMINERFILE="cgminer.alb10"
            CGMINERDEFAULTFILE="cgminer.default.alb10"
        fi
    fi
    if [ "$hash_board" = "HB12" ]; then
        if [ isH3Platform ]; then
            CGMINERFILE="cgminer.hash12.h3"
            CGMINERDEFAULTFILE="cgminer.default.hash12.h3"
        else
            CGMINERFILE="cgminer.hash12"
            CGMINERDEFAULTFILE="cgminer.default.hash12"
        fi
    fi
    if [ "$hash_board" = "HB10" ]; then
        CGMINERFILE="cgminer.hash10"
        CGMINERDEFAULTFILE="cgminer.default.hash10"
    fi

    if [ -f /etc/config/$CGMINERFILE ]; then
        DIFF=`cmp /etc/config/$CGMINERFILE /etc/config/cgminer`
        if [ ! -f /etc/config/cgminer -o "$DIFF" != "" ]; then
            cd /etc/config/
            rm -f cgminer
            ln -s $CGMINERFILE cgminer
            cd -
            logger "detect-cgminer-config: linking /etc/config/cgminer to /etc/config/$CGMINERFILE"
        else
            logger "detect-cgminer-config: /etc/config/cgminer remains unchanged"
        fi
    fi
    if [ -f /etc/config/$CGMINERDEFAULTFILE ]; then
        DIFF=`cmp /etc/config/$CGMINERDEFAULTFILE /etc/config/cgminer.default`
        if [ ! -f /etc/config/cgminer.default -o "$DIFF" != "" ]; then
            cd /etc/config/
            rm -f cgminer.default
            ln -s $CGMINERDEFAULTFILE cgminer.default
            cd -
            logger "detect-cgminer-config: linking /etc/config/cgminer.default to /etc/config/$CGMINERDEFAULTFILE"
        else
            logger "detect-cgminer-config: /etc/config/cgminer.default remains unchanged"
        fi
    fi
}
